{{- if .Values.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app_name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "standard-chart.common.metadataLabels" $ | nindent 4 }}
data:
  {{- if .Values.configmap }}
  {{- range $key, $val := .Values.configmap.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
{{- end }}