{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app_name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "standard-chart.common.metadataLabels" $ | nindent 4 }}
  {{- if .Values.secret.annotations }}
  annotations:
    {{- range $key, $val := .Values.secret.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
 {{- end }}
type: Opaque
data:
  {{- range $key, $val := .Values.secret.data }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
