app_name: biz-api
namespace: eshop
umbrella: users
clusterName: eshop-k8s

image:
  repository: al/biz-api
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # TODO:
    cert-manager.io/cluster-issuer: "letsencrypt-test"
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: '*.eshop.local'
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

deployment:
  progress_deadline_seconds: 600
  replicas: 1
  resources:
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 128Mi
  liveness:
    path: /liveness
    failure_threshold: 3
    initial_delay_seconds: 10
    period_seconds: 15
    success_threshold: 1
    timeout_seconds: 15
    port: 80
  readiness:
    path: /hc
    failure_threshold: 3
    timeoutSeconds: 5
    initial_delay_seconds: 90
    period_seconds: 60
    success_threshold: 1
    timeout_seconds: 15

probes:
  liveness:
    path: /liveness
    initialDelaySeconds: 10
    periodSeconds: 15
    port: 80
  readiness:
    path: /hc
    timeoutSeconds: 5
    initialDelaySeconds: 90
    periodSeconds: 60
    port: 80
